services:
  site:
    image: sharlles13/gerador_saudacao:version-1.0
    ports:
      - "80:80"
    depends_on:
      - ms-pessoas-aleatorias
      - ms-saudacoes-aleatorias
    networks:
      - backend

  ms-pessoas-aleatorias:
    image: sharlles13/ms-pessoas-aleatorias:1.0
    ports:
      - "8000:8000"
    networks:
      - backend

  ms-saudacoes-aleatorias:
    image: sharlles13/ms-saudacoes-aleatorias:1.0
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend: {}
